---
name: vlad-carlo-redis
director_uuid: <%= `bosh status --uuid`.strip %>

releases:
- name: vlad-carlo-redis-release
  version: latest

instance_groups:
- name: redis
  instances: 1
  vm_type: t2.micro
  persistent_disk: 1024
  stemcell: trusty
  networks:
  - name: services
  azs:
  - eu-west-1a
  jobs:
  - name: redis_server
    release: vlad-carlo-redis-release
    properties:
      redis:
        port: 1921
- name: broker
  instances: 1
  vm_type: t2.micro
  stemcell: trusty
  networks:
  - name: services
  azs:
  - eu-west-1a
  jobs:
  - name: redis_broker
    release: vlad-carlo-redis-release

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
